2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_setup.py:_flush():80] Configure stats pid to 87280
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_setup.py:_flush():80] Loading settings from /home/melih/.config/wandb/settings
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_setup.py:_flush():80] Loading settings from /home/melih/Documents/Bites_CPU_Analizi/wandb/settings
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/melih/Documents/Bites_CPU_Analizi/wandb/run-20250729_162708-yei1y52l/logs/debug.log
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/melih/Documents/Bites_CPU_Analizi/wandb/run-20250729_162708-yei1y52l/logs/debug-internal.log
2025-07-29 16:27:08,090 INFO    MainThread:87280 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f8ccf4e2a50>
2025-07-29 16:27:08,091 INFO    MainThread:87280 [wandb_init.py:init():830] calling init triggers
2025-07-29 16:27:08,091 INFO    MainThread:87280 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'architecture': 'SARIMA', 'optimizer': 'auto_arima', 'seasonal_period': 48, '_wandb': {}}
2025-07-29 16:27:08,091 INFO    MainThread:87280 [wandb_init.py:init():871] starting backend
2025-07-29 16:27:08,295 INFO    MainThread:87280 [wandb_init.py:init():874] sending inform_init request
2025-07-29 16:27:08,401 INFO    MainThread:87280 [wandb_init.py:init():882] backend started and connected
2025-07-29 16:27:08,402 INFO    MainThread:87280 [wandb_run.py:_label_probe_notebook():1304] probe notebook
2025-07-29 16:27:08,406 INFO    MainThread:87280 [wandb_init.py:init():953] updated telemetry
2025-07-29 16:27:08,409 INFO    MainThread:87280 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-29 16:27:09,207 INFO    MainThread:87280 [wandb_init.py:init():1029] starting run threads in backend
2025-07-29 16:27:09,259 INFO    MainThread:87280 [wandb_run.py:_console_start():2458] atexit reg
2025-07-29 16:27:09,259 INFO    MainThread:87280 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-29 16:27:09,259 INFO    MainThread:87280 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-29 16:27:09,259 INFO    MainThread:87280 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-29 16:27:09,260 INFO    MainThread:87280 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-29 16:35:31,305 WARNING MsgRouterThr:87280 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 231, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 216, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-29 16:35:31,384 INFO    MsgRouterThr:87280 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-29 16:35:32,129 INFO    MainThread:87280 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
